# Generated by Django 5.0.6 on 2024-11-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_image_alter_message_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='voice_message',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=5),
        ),
    ]
